"""
Application constants — countries, languages, currencies, email templates.
"""

SUPPORTED_COUNTRIES = {
    # ═══ EUROPE (34) ═══
    "ES": {"name": "Spain", "flag": "\U0001f1ea\U0001f1f8", "currency": "EUR", "languages": ["es", "en"]},
    "FR": {"name": "France", "flag": "\U0001f1eb\U0001f1f7", "currency": "EUR", "languages": ["fr", "en"]},
    "DE": {"name": "Germany", "flag": "\U0001f1e9\U0001f1ea", "currency": "EUR", "languages": ["de", "en"]},
    "IT": {"name": "Italy", "flag": "\U0001f1ee\U0001f1f9", "currency": "EUR", "languages": ["it", "en"]},
    "PT": {"name": "Portugal", "flag": "\U0001f1f5\U0001f1f9", "currency": "EUR", "languages": ["pt", "en"]},
    "NL": {"name": "Netherlands", "flag": "\U0001f1f3\U0001f1f1", "currency": "EUR", "languages": ["nl", "en"]},
    "BE": {"name": "Belgium", "flag": "\U0001f1e7\U0001f1ea", "currency": "EUR", "languages": ["nl", "fr", "en"]},
    "AT": {"name": "Austria", "flag": "\U0001f1e6\U0001f1f9", "currency": "EUR", "languages": ["de", "en"]},
    "IE": {"name": "Ireland", "flag": "\U0001f1ee\U0001f1ea", "currency": "EUR", "languages": ["en"]},
    "GR": {"name": "Greece", "flag": "\U0001f1ec\U0001f1f7", "currency": "EUR", "languages": ["el", "en"]},
    "FI": {"name": "Finland", "flag": "\U0001f1eb\U0001f1ee", "currency": "EUR", "languages": ["fi", "en"]},
    "SE": {"name": "Sweden", "flag": "\U0001f1f8\U0001f1ea", "currency": "SEK", "languages": ["sv", "en"]},
    "DK": {"name": "Denmark", "flag": "\U0001f1e9\U0001f1f0", "currency": "DKK", "languages": ["da", "en"]},
    "NO": {"name": "Norway", "flag": "\U0001f1f3\U0001f1f4", "currency": "NOK", "languages": ["no", "en"]},
    "PL": {"name": "Poland", "flag": "\U0001f1f5\U0001f1f1", "currency": "PLN", "languages": ["pl", "en"]},
    "CZ": {"name": "Czech Republic", "flag": "\U0001f1e8\U0001f1ff", "currency": "CZK", "languages": ["cs", "en"]},
    "RO": {"name": "Romania", "flag": "\U0001f1f7\U0001f1f4", "currency": "RON", "languages": ["ro", "en"]},
    "HU": {"name": "Hungary", "flag": "\U0001f1ed\U0001f1fa", "currency": "HUF", "languages": ["hu", "en"]},
    "CH": {"name": "Switzerland", "flag": "\U0001f1e8\U0001f1ed", "currency": "CHF", "languages": ["de", "fr", "it", "en"]},
    "LU": {"name": "Luxembourg", "flag": "\U0001f1f1\U0001f1fa", "currency": "EUR", "languages": ["fr", "de", "en"]},
    "HR": {"name": "Croatia", "flag": "\U0001f1ed\U0001f1f7", "currency": "EUR", "languages": ["hr", "en"]},
    "BG": {"name": "Bulgaria", "flag": "\U0001f1e7\U0001f1ec", "currency": "BGN", "languages": ["bg", "en"]},
    "SK": {"name": "Slovakia", "flag": "\U0001f1f8\U0001f1f0", "currency": "EUR", "languages": ["sk", "en"]},
    "SI": {"name": "Slovenia", "flag": "\U0001f1f8\U0001f1ee", "currency": "EUR", "languages": ["sl", "en"]},
    "LT": {"name": "Lithuania", "flag": "\U0001f1f1\U0001f1f9", "currency": "EUR", "languages": ["lt", "en"]},
    "LV": {"name": "Latvia", "flag": "\U0001f1f1\U0001f1fb", "currency": "EUR", "languages": ["lv", "en"]},
    "EE": {"name": "Estonia", "flag": "\U0001f1ea\U0001f1ea", "currency": "EUR", "languages": ["et", "en"]},
    "IS": {"name": "Iceland", "flag": "\U0001f1ee\U0001f1f8", "currency": "ISK", "languages": ["is", "en"]},
    "GB": {"name": "United Kingdom", "flag": "\U0001f1ec\U0001f1e7", "currency": "GBP", "languages": ["en"]},
    "RS": {"name": "Serbia", "flag": "\U0001f1f7\U0001f1f8", "currency": "RSD", "languages": ["sr", "en"]},
    "BA": {"name": "Bosnia & Herzegovina", "flag": "\U0001f1e7\U0001f1e6", "currency": "BAM", "languages": ["sr", "hr", "en"]},
    "ME": {"name": "Montenegro", "flag": "\U0001f1f2\U0001f1ea", "currency": "EUR", "languages": ["sr", "en"]},
    "MK": {"name": "North Macedonia", "flag": "\U0001f1f2\U0001f1f0", "currency": "MKD", "languages": ["sr", "en"]},
    "AL": {"name": "Albania", "flag": "\U0001f1e6\U0001f1f1", "currency": "ALL", "languages": ["en"]},
    "MD": {"name": "Moldova", "flag": "\U0001f1f2\U0001f1e9", "currency": "MDL", "languages": ["ro", "ru", "en"]},
    "UA": {"name": "Ukraine", "flag": "\U0001f1fa\U0001f1e6", "currency": "UAH", "languages": ["uk", "en"]},
    "BY": {"name": "Belarus", "flag": "\U0001f1e7\U0001f1fe", "currency": "BYN", "languages": ["ru", "en"]},
    "MT": {"name": "Malta", "flag": "\U0001f1f2\U0001f1f9", "currency": "EUR", "languages": ["en"]},
    "CY": {"name": "Cyprus", "flag": "\U0001f1e8\U0001f1fe", "currency": "EUR", "languages": ["el", "tr", "en"]},
    # ═══ AMERICAS (22) ═══
    "US": {"name": "United States", "flag": "\U0001f1fa\U0001f1f8", "currency": "USD", "languages": ["en", "es"]},
    "CA": {"name": "Canada", "flag": "\U0001f1e8\U0001f1e6", "currency": "CAD", "languages": ["en", "fr"]},
    "MX": {"name": "Mexico", "flag": "\U0001f1f2\U0001f1fd", "currency": "MXN", "languages": ["es", "en"]},
    "BR": {"name": "Brazil", "flag": "\U0001f1e7\U0001f1f7", "currency": "BRL", "languages": ["pt", "en"]},
    "AR": {"name": "Argentina", "flag": "\U0001f1e6\U0001f1f7", "currency": "ARS", "languages": ["es", "en"]},
    "CL": {"name": "Chile", "flag": "\U0001f1e8\U0001f1f1", "currency": "CLP", "languages": ["es", "en"]},
    "CO": {"name": "Colombia", "flag": "\U0001f1e8\U0001f1f4", "currency": "COP", "languages": ["es", "en"]},
    "PE": {"name": "Peru", "flag": "\U0001f1f5\U0001f1ea", "currency": "PEN", "languages": ["es", "en"]},
    "UY": {"name": "Uruguay", "flag": "\U0001f1fa\U0001f1fe", "currency": "UYU", "languages": ["es", "en"]},
    "CR": {"name": "Costa Rica", "flag": "\U0001f1e8\U0001f1f7", "currency": "CRC", "languages": ["es", "en"]},
    "PA": {"name": "Panama", "flag": "\U0001f1f5\U0001f1e6", "currency": "USD", "languages": ["es", "en"]},
    "EC": {"name": "Ecuador", "flag": "\U0001f1ea\U0001f1e8", "currency": "USD", "languages": ["es", "en"]},
    "BO": {"name": "Bolivia", "flag": "\U0001f1e7\U0001f1f4", "currency": "BOB", "languages": ["es", "en"]},
    "PY": {"name": "Paraguay", "flag": "\U0001f1f5\U0001f1fe", "currency": "PYG", "languages": ["es", "en"]},
    "DO": {"name": "Dominican Republic", "flag": "\U0001f1e9\U0001f1f4", "currency": "DOP", "languages": ["es", "en"]},
    "GT": {"name": "Guatemala", "flag": "\U0001f1ec\U0001f1f9", "currency": "GTQ", "languages": ["es", "en"]},
    "HN": {"name": "Honduras", "flag": "\U0001f1ed\U0001f1f3", "currency": "HNL", "languages": ["es", "en"]},
    "SV": {"name": "El Salvador", "flag": "\U0001f1f8\U0001f1fb", "currency": "USD", "languages": ["es", "en"]},
    "NI": {"name": "Nicaragua", "flag": "\U0001f1f3\U0001f1ee", "currency": "NIO", "languages": ["es", "en"]},
    "PR": {"name": "Puerto Rico", "flag": "\U0001f1f5\U0001f1f7", "currency": "USD", "languages": ["es", "en"]},
    "JM": {"name": "Jamaica", "flag": "\U0001f1ef\U0001f1f2", "currency": "JMD", "languages": ["en"]},
    "TT": {"name": "Trinidad & Tobago", "flag": "\U0001f1f9\U0001f1f9", "currency": "TTD", "languages": ["en"]},
    # ═══ ASIA-PACIFIC (25) ═══
    "JP": {"name": "Japan", "flag": "\U0001f1ef\U0001f1f5", "currency": "JPY", "languages": ["ja", "en"]},
    "KR": {"name": "South Korea", "flag": "\U0001f1f0\U0001f1f7", "currency": "KRW", "languages": ["ko", "en"]},
    "CN": {"name": "China", "flag": "\U0001f1e8\U0001f1f3", "currency": "CNY", "languages": ["zh", "en"]},
    "IN": {"name": "India", "flag": "\U0001f1ee\U0001f1f3", "currency": "INR", "languages": ["hi", "en"]},
    "AU": {"name": "Australia", "flag": "\U0001f1e6\U0001f1fa", "currency": "AUD", "languages": ["en"]},
    "NZ": {"name": "New Zealand", "flag": "\U0001f1f3\U0001f1ff", "currency": "NZD", "languages": ["en"]},
    "SG": {"name": "Singapore", "flag": "\U0001f1f8\U0001f1ec", "currency": "SGD", "languages": ["en", "zh"]},
    "HK": {"name": "Hong Kong", "flag": "\U0001f1ed\U0001f1f0", "currency": "HKD", "languages": ["zh", "en"]},
    "TW": {"name": "Taiwan", "flag": "\U0001f1f9\U0001f1fc", "currency": "TWD", "languages": ["zh", "en"]},
    "TH": {"name": "Thailand", "flag": "\U0001f1f9\U0001f1ed", "currency": "THB", "languages": ["th", "en"]},
    "MY": {"name": "Malaysia", "flag": "\U0001f1f2\U0001f1fe", "currency": "MYR", "languages": ["ms", "en"]},
    "PH": {"name": "Philippines", "flag": "\U0001f1f5\U0001f1ed", "currency": "PHP", "languages": ["en", "tl"]},
    "ID": {"name": "Indonesia", "flag": "\U0001f1ee\U0001f1e9", "currency": "IDR", "languages": ["id", "en"]},
    "VN": {"name": "Vietnam", "flag": "\U0001f1fb\U0001f1f3", "currency": "VND", "languages": ["vi", "en"]},
    "BD": {"name": "Bangladesh", "flag": "\U0001f1e7\U0001f1e9", "currency": "BDT", "languages": ["bn", "en"]},
    "PK": {"name": "Pakistan", "flag": "\U0001f1f5\U0001f1f0", "currency": "PKR", "languages": ["ur", "en"]},
    "LK": {"name": "Sri Lanka", "flag": "\U0001f1f1\U0001f1f0", "currency": "LKR", "languages": ["si", "ta", "en"]},
    "NP": {"name": "Nepal", "flag": "\U0001f1f3\U0001f1f5", "currency": "NPR", "languages": ["ne", "en"]},
    "MM": {"name": "Myanmar", "flag": "\U0001f1f2\U0001f1f2", "currency": "MMK", "languages": ["my", "en"]},
    "KH": {"name": "Cambodia", "flag": "\U0001f1f0\U0001f1ed", "currency": "KHR", "languages": ["km", "en"]},
    "LA": {"name": "Laos", "flag": "\U0001f1f1\U0001f1e6", "currency": "LAK", "languages": ["lo", "en"]},
    "MN": {"name": "Mongolia", "flag": "\U0001f1f2\U0001f1f3", "currency": "MNT", "languages": ["en"]},
    "BN": {"name": "Brunei", "flag": "\U0001f1e7\U0001f1f3", "currency": "BND", "languages": ["ms", "en"]},
    "MV": {"name": "Maldives", "flag": "\U0001f1f2\U0001f1fb", "currency": "MVR", "languages": ["en"]},
    "FJ": {"name": "Fiji", "flag": "\U0001f1eb\U0001f1ef", "currency": "FJD", "languages": ["en"]},
    # ═══ MIDDLE EAST & CENTRAL ASIA (18) ═══
    "AE": {"name": "UAE", "flag": "\U0001f1e6\U0001f1ea", "currency": "AED", "languages": ["ar", "en"]},
    "SA": {"name": "Saudi Arabia", "flag": "\U0001f1f8\U0001f1e6", "currency": "SAR", "languages": ["ar", "en"]},
    "IL": {"name": "Israel", "flag": "\U0001f1ee\U0001f1f1", "currency": "ILS", "languages": ["he", "en"]},
    "QA": {"name": "Qatar", "flag": "\U0001f1f6\U0001f1e6", "currency": "QAR", "languages": ["ar", "en"]},
    "KW": {"name": "Kuwait", "flag": "\U0001f1f0\U0001f1fc", "currency": "KWD", "languages": ["ar", "en"]},
    "BH": {"name": "Bahrain", "flag": "\U0001f1e7\U0001f1ed", "currency": "BHD", "languages": ["ar", "en"]},
    "OM": {"name": "Oman", "flag": "\U0001f1f4\U0001f1f2", "currency": "OMR", "languages": ["ar", "en"]},
    "JO": {"name": "Jordan", "flag": "\U0001f1ef\U0001f1f4", "currency": "JOD", "languages": ["ar", "en"]},
    "LB": {"name": "Lebanon", "flag": "\U0001f1f1\U0001f1e7", "currency": "LBP", "languages": ["ar", "fr", "en"]},
    "IQ": {"name": "Iraq", "flag": "\U0001f1ee\U0001f1f6", "currency": "IQD", "languages": ["ar", "en"]},
    "TR": {"name": "Turkey", "flag": "\U0001f1f9\U0001f1f7", "currency": "TRY", "languages": ["tr", "en"]},
    "GE": {"name": "Georgia", "flag": "\U0001f1ec\U0001f1ea", "currency": "GEL", "languages": ["ka", "en"]},
    "AM": {"name": "Armenia", "flag": "\U0001f1e6\U0001f1f2", "currency": "AMD", "languages": ["hy", "en"]},
    "AZ": {"name": "Azerbaijan", "flag": "\U0001f1e6\U0001f1ff", "currency": "AZN", "languages": ["az", "en"]},
    "KZ": {"name": "Kazakhstan", "flag": "\U0001f1f0\U0001f1ff", "currency": "KZT", "languages": ["kk", "ru", "en"]},
    "UZ": {"name": "Uzbekistan", "flag": "\U0001f1fa\U0001f1ff", "currency": "UZS", "languages": ["uz", "ru", "en"]},
    "KG": {"name": "Kyrgyzstan", "flag": "\U0001f1f0\U0001f1ec", "currency": "KGS", "languages": ["ru", "en"]},
    "TJ": {"name": "Tajikistan", "flag": "\U0001f1f9\U0001f1ef", "currency": "TJS", "languages": ["ru", "en"]},
    # ═══ AFRICA (30) ═══
    "EG": {"name": "Egypt", "flag": "\U0001f1ea\U0001f1ec", "currency": "EGP", "languages": ["ar", "en"]},
    "MA": {"name": "Morocco", "flag": "\U0001f1f2\U0001f1e6", "currency": "MAD", "languages": ["ar", "fr", "en"]},
    "ZA": {"name": "South Africa", "flag": "\U0001f1ff\U0001f1e6", "currency": "ZAR", "languages": ["en", "af"]},
    "NG": {"name": "Nigeria", "flag": "\U0001f1f3\U0001f1ec", "currency": "NGN", "languages": ["en"]},
    "KE": {"name": "Kenya", "flag": "\U0001f1f0\U0001f1ea", "currency": "KES", "languages": ["sw", "en"]},
    "ET": {"name": "Ethiopia", "flag": "\U0001f1ea\U0001f1f9", "currency": "ETB", "languages": ["am", "en"]},
    "GH": {"name": "Ghana", "flag": "\U0001f1ec\U0001f1ed", "currency": "GHS", "languages": ["en"]},
    "TZ": {"name": "Tanzania", "flag": "\U0001f1f9\U0001f1ff", "currency": "TZS", "languages": ["sw", "en"]},
    "UG": {"name": "Uganda", "flag": "\U0001f1fa\U0001f1ec", "currency": "UGX", "languages": ["sw", "en"]},
    "RW": {"name": "Rwanda", "flag": "\U0001f1f7\U0001f1fc", "currency": "RWF", "languages": ["en", "fr"]},
    "SN": {"name": "Senegal", "flag": "\U0001f1f8\U0001f1f3", "currency": "XOF", "languages": ["fr", "en"]},
    "CI": {"name": "Ivory Coast", "flag": "\U0001f1e8\U0001f1ee", "currency": "XOF", "languages": ["fr", "en"]},
    "CM": {"name": "Cameroon", "flag": "\U0001f1e8\U0001f1f2", "currency": "XAF", "languages": ["fr", "en"]},
    "TN": {"name": "Tunisia", "flag": "\U0001f1f9\U0001f1f3", "currency": "TND", "languages": ["ar", "fr", "en"]},
    "DZ": {"name": "Algeria", "flag": "\U0001f1e9\U0001f1ff", "currency": "DZD", "languages": ["ar", "fr", "en"]},
    "LY": {"name": "Libya", "flag": "\U0001f1f1\U0001f1fe", "currency": "LYD", "languages": ["ar", "en"]},
    "AO": {"name": "Angola", "flag": "\U0001f1e6\U0001f1f4", "currency": "AOA", "languages": ["pt", "en"]},
    "MZ": {"name": "Mozambique", "flag": "\U0001f1f2\U0001f1ff", "currency": "MZN", "languages": ["pt", "en"]},
    "MU": {"name": "Mauritius", "flag": "\U0001f1f2\U0001f1fa", "currency": "MUR", "languages": ["en", "fr"]},
    "MG": {"name": "Madagascar", "flag": "\U0001f1f2\U0001f1ec", "currency": "MGA", "languages": ["fr", "en"]},
    "NA": {"name": "Namibia", "flag": "\U0001f1f3\U0001f1e6", "currency": "NAD", "languages": ["en", "af"]},
    "BW": {"name": "Botswana", "flag": "\U0001f1e7\U0001f1fc", "currency": "BWP", "languages": ["en"]},
    "ZM": {"name": "Zambia", "flag": "\U0001f1ff\U0001f1f2", "currency": "ZMW", "languages": ["en"]},
    "ZW": {"name": "Zimbabwe", "flag": "\U0001f1ff\U0001f1fc", "currency": "USD", "languages": ["en"]},
    "CD": {"name": "DR Congo", "flag": "\U0001f1e8\U0001f1e9", "currency": "CDF", "languages": ["fr", "en"]},
    "ML": {"name": "Mali", "flag": "\U0001f1f2\U0001f1f1", "currency": "XOF", "languages": ["fr", "en"]},
    "BF": {"name": "Burkina Faso", "flag": "\U0001f1e7\U0001f1eb", "currency": "XOF", "languages": ["fr", "en"]},
    "NE": {"name": "Niger", "flag": "\U0001f1f3\U0001f1ea", "currency": "XOF", "languages": ["fr", "en"]},
    "SD": {"name": "Sudan", "flag": "\U0001f1f8\U0001f1e9", "currency": "SDG", "languages": ["ar", "en"]},
    "SO": {"name": "Somalia", "flag": "\U0001f1f8\U0001f1f4", "currency": "SOS", "languages": ["en", "ar"]},
    # ═══ RUSSIA & CIS ═══
    "RU": {"name": "Russia", "flag": "\U0001f1f7\U0001f1fa", "currency": "RUB", "languages": ["ru", "en"]},
    # ═══════════════════════════════════════════════════════════
    # Excluded: KP (North Korea), SY (Syria), sanctioned entities
    # ═══════════════════════════════════════════════════════════
}

SUPPORTED_LANGUAGES = {
    "en": {"name": "English", "native": "English"},
    "es": {"name": "Spanish", "native": "Español"},
    "fr": {"name": "French", "native": "Français"},
    "de": {"name": "German", "native": "Deutsch"},
    "pt": {"name": "Portuguese", "native": "Português"},
    "zh": {"name": "Mandarin Chinese", "native": "中文"},
    "ja": {"name": "Japanese", "native": "日本語"},
    "ko": {"name": "Korean", "native": "한국어"},
    "hi": {"name": "Hindi", "native": "हिन्दी"},
    "ar": {"name": "Arabic", "native": "العربية"},
    "ru": {"name": "Russian", "native": "Русский"},
    "it": {"name": "Italian", "native": "Italiano"},
    "nl": {"name": "Dutch", "native": "Nederlands"},
    "pl": {"name": "Polish", "native": "Polski"},
    "tr": {"name": "Turkish", "native": "Türkçe"},
    "sv": {"name": "Swedish", "native": "Svenska"},
    "ro": {"name": "Romanian", "native": "Română"},
    "cs": {"name": "Czech", "native": "Čeština"},
    "el": {"name": "Greek", "native": "Ελληνικά"},
    "hu": {"name": "Hungarian", "native": "Magyar"},
    "uk": {"name": "Ukrainian", "native": "Українська"},
    "th": {"name": "Thai", "native": "ไทย"},
    "vi": {"name": "Vietnamese", "native": "Tiếng Việt"},
    "id": {"name": "Indonesian", "native": "Bahasa Indonesia"},
    "tl": {"name": "Filipino", "native": "Filipino"},
    "bn": {"name": "Bengali", "native": "বাংলা"},
    "ta": {"name": "Tamil", "native": "தமிழ்"},
    "ur": {"name": "Urdu", "native": "اردو"},
    "fa": {"name": "Persian", "native": "فارسی"},
    "sw": {"name": "Swahili", "native": "Kiswahili"},
    "da": {"name": "Danish", "native": "Dansk"},
    "no": {"name": "Norwegian", "native": "Norsk"},
    "fi": {"name": "Finnish", "native": "Suomi"},
    "he": {"name": "Hebrew", "native": "עברית"},
    "ms": {"name": "Malay", "native": "Bahasa Melayu"},
    "mr": {"name": "Marathi", "native": "मराठी"},
    "te": {"name": "Telugu", "native": "తెలుగు"},
    "pa": {"name": "Punjabi", "native": "ਪੰਜਾਬੀ"},
    "gu": {"name": "Gujarati", "native": "ગુજરાતી"},
    "kn": {"name": "Kannada", "native": "ಕನ್ನಡ"},
    "ml": {"name": "Malayalam", "native": "മലയാളം"},
    "my": {"name": "Burmese", "native": "မြန်မာ"},
    "km": {"name": "Khmer", "native": "ខ្មែរ"},
    "lo": {"name": "Lao", "native": "ລາວ"},
    "ne": {"name": "Nepali", "native": "नेपाली"},
    "si": {"name": "Sinhala", "native": "සිංහල"},
    "ka": {"name": "Georgian", "native": "ქართული"},
    "hy": {"name": "Armenian", "native": "Հայերեն"},
    "az": {"name": "Azerbaijani", "native": "Azərbaycan"},
    "uz": {"name": "Uzbek", "native": "Oʻzbek"},
    "kk": {"name": "Kazakh", "native": "Қазақ"},
    "hr": {"name": "Croatian", "native": "Hrvatski"},
    "sk": {"name": "Slovak", "native": "Slovenčina"},
    "bg": {"name": "Bulgarian", "native": "Български"},
    "sr": {"name": "Serbian", "native": "Српски"},
    "lt": {"name": "Lithuanian", "native": "Lietuvių"},
    "lv": {"name": "Latvian", "native": "Latviešu"},
    "et": {"name": "Estonian", "native": "Eesti"},
    "af": {"name": "Afrikaans", "native": "Afrikaans"},
    "am": {"name": "Amharic", "native": "አማርኛ"},
}

TRANSLATION_LANGUAGES = list(SUPPORTED_LANGUAGES.keys())

SUPPORTED_CURRENCIES = {
    "EUR": {"symbol": "\u20ac", "name": "Euro"},
    "USD": {"symbol": "$", "name": "US Dollar"},
    "GBP": {"symbol": "\u00a3", "name": "British Pound"},
    "JPY": {"symbol": "\u00a5", "name": "Japanese Yen"},
    "KRW": {"symbol": "\u20a9", "name": "Korean Won"},
    "CNY": {"symbol": "\u00a5", "name": "Chinese Yuan"},
    "INR": {"symbol": "\u20b9", "name": "Indian Rupee"},
    "AED": {"symbol": "\u062f.\u0625", "name": "UAE Dirham"},
    "SAR": {"symbol": "\ufdfc", "name": "Saudi Riyal"},
    "BRL": {"symbol": "R$", "name": "Brazilian Real"},
    "MXN": {"symbol": "$", "name": "Mexican Peso"},
    "CAD": {"symbol": "$", "name": "Canadian Dollar"},
    "AUD": {"symbol": "$", "name": "Australian Dollar"},
    "NZD": {"symbol": "$", "name": "New Zealand Dollar"},
    "CHF": {"symbol": "Fr.", "name": "Swiss Franc"},
    "SEK": {"symbol": "kr", "name": "Swedish Krona"},
    "NOK": {"symbol": "kr", "name": "Norwegian Krone"},
    "DKK": {"symbol": "kr", "name": "Danish Krone"},
    "PLN": {"symbol": "z\u0142", "name": "Polish Zloty"},
    "CZK": {"symbol": "K\u010d", "name": "Czech Koruna"},
    "HUF": {"symbol": "Ft", "name": "Hungarian Forint"},
    "RON": {"symbol": "lei", "name": "Romanian Leu"},
    "TRY": {"symbol": "\u20ba", "name": "Turkish Lira"},
    "SGD": {"symbol": "$", "name": "Singapore Dollar"},
    "HKD": {"symbol": "$", "name": "Hong Kong Dollar"},
    "TWD": {"symbol": "$", "name": "Taiwan Dollar"},
    "THB": {"symbol": "\u0e3f", "name": "Thai Baht"},
    "MYR": {"symbol": "RM", "name": "Malaysian Ringgit"},
    "PHP": {"symbol": "\u20b1", "name": "Philippine Peso"},
    "IDR": {"symbol": "Rp", "name": "Indonesian Rupiah"},
    "VND": {"symbol": "\u20ab", "name": "Vietnamese Dong"},
    "ILS": {"symbol": "\u20aa", "name": "Israeli Shekel"},
    "QAR": {"symbol": "\ufdfc", "name": "Qatari Riyal"},
    "KWD": {"symbol": "\u062f.\u0643", "name": "Kuwaiti Dinar"},
    "ZAR": {"symbol": "R", "name": "South African Rand"},
    "NGN": {"symbol": "\u20a6", "name": "Nigerian Naira"},
    "EGP": {"symbol": "\u00a3", "name": "Egyptian Pound"},
    "MAD": {"symbol": "MAD", "name": "Moroccan Dirham"},
    "ARS": {"symbol": "$", "name": "Argentine Peso"},
    "CLP": {"symbol": "$", "name": "Chilean Peso"},
    "COP": {"symbol": "$", "name": "Colombian Peso"},
    "PEN": {"symbol": "S/", "name": "Peruvian Sol"},
    # New currencies for expanded markets
    "UYU": {"symbol": "$", "name": "Uruguayan Peso"},
    "CRC": {"symbol": "\u20a1", "name": "Costa Rican Colon"},
    "BOB": {"symbol": "Bs", "name": "Bolivian Boliviano"},
    "PYG": {"symbol": "\u20b2", "name": "Paraguayan Guarani"},
    "DOP": {"symbol": "$", "name": "Dominican Peso"},
    "GTQ": {"symbol": "Q", "name": "Guatemalan Quetzal"},
    "HNL": {"symbol": "L", "name": "Honduran Lempira"},
    "NIO": {"symbol": "C$", "name": "Nicaraguan Cordoba"},
    "JMD": {"symbol": "$", "name": "Jamaican Dollar"},
    "TTD": {"symbol": "$", "name": "Trinidad Dollar"},
    "BDT": {"symbol": "\u09f3", "name": "Bangladeshi Taka"},
    "PKR": {"symbol": "\u20a8", "name": "Pakistani Rupee"},
    "LKR": {"symbol": "Rs", "name": "Sri Lankan Rupee"},
    "NPR": {"symbol": "Rs", "name": "Nepalese Rupee"},
    "MMK": {"symbol": "K", "name": "Myanmar Kyat"},
    "KHR": {"symbol": "\u17db", "name": "Cambodian Riel"},
    "LAK": {"symbol": "\u20ad", "name": "Lao Kip"},
    "MNT": {"symbol": "\u20ae", "name": "Mongolian Tugrik"},
    "BND": {"symbol": "$", "name": "Brunei Dollar"},
    "MVR": {"symbol": "Rf", "name": "Maldivian Rufiyaa"},
    "FJD": {"symbol": "$", "name": "Fijian Dollar"},
    "BHD": {"symbol": "BD", "name": "Bahraini Dinar"},
    "OMR": {"symbol": "OMR", "name": "Omani Rial"},
    "JOD": {"symbol": "JD", "name": "Jordanian Dinar"},
    "LBP": {"symbol": "LL", "name": "Lebanese Pound"},
    "IQD": {"symbol": "IQD", "name": "Iraqi Dinar"},
    "GEL": {"symbol": "\u20be", "name": "Georgian Lari"},
    "AMD": {"symbol": "\u058f", "name": "Armenian Dram"},
    "AZN": {"symbol": "\u20bc", "name": "Azerbaijani Manat"},
    "KZT": {"symbol": "\u20b8", "name": "Kazakhstani Tenge"},
    "UZS": {"symbol": "UZS", "name": "Uzbekistani Som"},
    "KGS": {"symbol": "KGS", "name": "Kyrgyzstani Som"},
    "TJS": {"symbol": "TJS", "name": "Tajikistani Somoni"},
    "RSD": {"symbol": "din", "name": "Serbian Dinar"},
    "BAM": {"symbol": "KM", "name": "Bosnian Mark"},
    "MKD": {"symbol": "den", "name": "Macedonian Denar"},
    "ALL": {"symbol": "L", "name": "Albanian Lek"},
    "MDL": {"symbol": "L", "name": "Moldovan Leu"},
    "UAH": {"symbol": "\u20b4", "name": "Ukrainian Hryvnia"},
    "BYN": {"symbol": "Br", "name": "Belarusian Ruble"},
    "ISK": {"symbol": "kr", "name": "Icelandic Krona"},
    "BGN": {"symbol": "lv", "name": "Bulgarian Lev"},
    "KES": {"symbol": "KSh", "name": "Kenyan Shilling"},
    "ETB": {"symbol": "Br", "name": "Ethiopian Birr"},
    "GHS": {"symbol": "\u20b5", "name": "Ghanaian Cedi"},
    "TZS": {"symbol": "TSh", "name": "Tanzanian Shilling"},
    "UGX": {"symbol": "USh", "name": "Ugandan Shilling"},
    "RWF": {"symbol": "FRw", "name": "Rwandan Franc"},
    "XOF": {"symbol": "CFA", "name": "West African CFA Franc"},
    "XAF": {"symbol": "FCFA", "name": "Central African CFA Franc"},
    "TND": {"symbol": "DT", "name": "Tunisian Dinar"},
    "DZD": {"symbol": "DA", "name": "Algerian Dinar"},
    "LYD": {"symbol": "LD", "name": "Libyan Dinar"},
    "AOA": {"symbol": "Kz", "name": "Angolan Kwanza"},
    "MZN": {"symbol": "MT", "name": "Mozambican Metical"},
    "MUR": {"symbol": "Rs", "name": "Mauritian Rupee"},
    "MGA": {"symbol": "Ar", "name": "Malagasy Ariary"},
    "NAD": {"symbol": "$", "name": "Namibian Dollar"},
    "BWP": {"symbol": "P", "name": "Botswana Pula"},
    "ZMW": {"symbol": "ZK", "name": "Zambian Kwacha"},
    "CDF": {"symbol": "FC", "name": "Congolese Franc"},
    "SDG": {"symbol": "SDG", "name": "Sudanese Pound"},
    "SOS": {"symbol": "Sh", "name": "Somali Shilling"},
    "RUB": {"symbol": "\u20bd", "name": "Russian Ruble"},
}

EMAIL_TEMPLATES = {
    "verification": {
        "es": {
            "subject": "Verifica tu cuenta - Hispaloshop",
            "title": "Verifica tu cuenta",
            "body": "Introduce este c\u00f3digo en tu panel para activar tu cuenta:",
            "expires": "Este c\u00f3digo expira en 24 horas.",
            "ignore": "Si no has solicitado esta verificaci\u00f3n, ignora este email."
        },
        "en": {
            "subject": "Verify your account - Hispaloshop",
            "title": "Verify your account",
            "body": "Enter this code in your dashboard to activate your account:",
            "expires": "This code expires in 24 hours.",
            "ignore": "If you didn't request this verification, please ignore this email."
        },
        "ko": {
            "subject": "\uacc4\uc815 \uc778\uc99d - Hispaloshop",
            "title": "\uacc4\uc815 \uc778\uc99d",
            "body": "\uc544\ub798 \ucf54\ub4dc\ub97c \ub300\uc2dc\ubcf4\ub4dc\uc5d0 \uc785\ub825\ud558\uc5ec \uacc4\uc815\uc744 \ud65c\uc131\ud654\ud558\uc138\uc694:",
            "expires": "\uc774 \ucf54\ub4dc\ub294 24\uc2dc\uac04 \ud6c4\uc5d0 \ub9cc\ub8cc\ub429\ub2c8\ub2e4.",
            "ignore": "\uc774 \uc778\uc99d\uc744 \uc694\uccad\ud558\uc9c0 \uc54a\uc73c\uc168\ub2e4\uba74 \uc774 \uc774\uba54\uc77c\uc744 \ubb34\uc2dc\ud558\uc138\uc694."
        }
    },
    "password_reset": {
        "es": {
            "subject": "Restablecer contrase\u00f1a - Hispaloshop",
            "title": "Restablecer contrase\u00f1a",
            "body": "Haz clic en el bot\u00f3n de abajo para restablecer tu contrase\u00f1a:",
            "button": "Restablecer Contrase\u00f1a",
            "expires": "Este enlace expira en 24 horas.",
            "ignore": "Si no solicitaste esto, ignora este email."
        },
        "en": {
            "subject": "Reset your password - Hispaloshop",
            "title": "Reset your password",
            "body": "Click the button below to reset your password:",
            "button": "Reset Password",
            "expires": "This link expires in 24 hours.",
            "ignore": "If you didn't request this, please ignore this email."
        },
        "ko": {
            "subject": "\ube44\ubc00\ubc88\ud638 \uc7ac\uc124\uc815 - Hispaloshop",
            "title": "\ube44\ubc00\ubc88\ud638 \uc7ac\uc124\uc815",
            "body": "\uc544\ub798 \ubc84\ud2bc\uc744 \ud074\ub9ad\ud558\uc5ec \ube44\ubc00\ubc88\ud638\ub97c \uc7ac\uc124\uc815\ud558\uc138\uc694:",
            "button": "\ube44\ubc00\ubc88\ud638 \uc7ac\uc124\uc815",
            "expires": "\uc774 \ub9c1\ud06c\ub294 24\uc2dc\uac04 \ud6c4\uc5d0 \ub9cc\ub8cc\ub429\ub2c8\ub2e4.",
            "ignore": "\uc694\uccad\ud558\uc9c0 \uc54a\uc73c\uc168\ub2e4\uba74 \uc774 \uc774\uba54\uc77c\uc744 \ubb34\uc2dc\ud558\uc138\uc694."
        }
    }
}


def get_email_template(template_name: str, language: str = "es") -> dict:
    """Get email template by name and language"""
    if language not in ["es", "en", "ko"]:
        language = "en"
    return EMAIL_TEMPLATES.get(template_name, {}).get(
        language, EMAIL_TEMPLATES.get(template_name, {}).get("en", {})
    )
