import {
  Apple,
  Baby,
  Beef,
  Coffee,
  Cookie,
  Croissant,
  Dog,
  Droplets,
  Dumbbell,
  Flame,
  Globe2,
  Leaf,
  Milk,
  Package,
  Snowflake,
  WheatOff,
  Wine,
  Zap,
} from 'lucide-react';

export const CATEGORY_CONFIG = [
  {
    slug: 'aceites-vinagres',
    label: 'Aceites & Vinagres',
    shortLabel: 'Aceites',
    icon: Droplets,
    bg: 'bg-emerald-50',
    color: 'text-emerald-700',
    border: 'border-emerald-100',
    description: 'Aceites de oliva, vinagres artesanos y aliños con origen claro.',
    fallbackCount: 47,
    aliases: ['aceites-vinagres', 'aceite-condimentos'],
  },
  {
    slug: 'conservas-mermeladas',
    label: 'Conservas & Mermeladas',
    shortLabel: 'Conservas',
    icon: Package,
    bg: 'bg-amber-50',
    color: 'text-amber-700',
    border: 'border-amber-100',
    description: 'Tarros pequeños, recetas lentas y sabor de despensa bien hecha.',
    fallbackCount: 34,
    aliases: ['conservas-mermeladas', 'conservas'],
  },
  {
    slug: 'quesos-lacteos',
    label: 'Quesos & Lacteos',
    shortLabel: 'Quesos',
    icon: Milk,
    bg: 'bg-yellow-50',
    color: 'text-yellow-700',
    border: 'border-yellow-100',
    description: 'Quesos curados, yogures y lacteos de pequenos elaboradores.',
    fallbackCount: 29,
    aliases: ['quesos-lacteos', 'quesos', 'lacteos'],
  },
  {
    slug: 'embutidos-curados',
    label: 'Embutidos & Curados',
    shortLabel: 'Embutidos',
    icon: Beef,
    bg: 'bg-rose-50',
    color: 'text-rose-700',
    border: 'border-rose-100',
    description: 'Jamones, lomos y curados con elaboracion lenta y trazable.',
    fallbackCount: 21,
    aliases: ['embutidos-curados', 'carnes-huevos'],
  },
  {
    slug: 'panadería-dulces',
    label: 'Panadería & Dulces',
    shortLabel: 'Panadería',
    icon: Croissant,
    bg: 'bg-orange-50',
    color: 'text-orange-700',
    border: 'border-orange-100',
    description: 'Hornadas artesanas, galletas honestas y dulces de obrador.',
    fallbackCount: 39,
    aliases: ['panadería-dulces', 'panadería'],
  },
  {
    slug: 'vinos-bebidas',
    label: 'Vinos & Bebidas',
    shortLabel: 'Bebidas',
    icon: Wine,
    bg: 'bg-fuchsia-50',
    color: 'text-fuchsia-700',
    border: 'border-fuchsia-100',
    description: 'Botellas con historia, bodegas pequeñas y bebidas de autor.',
    fallbackCount: 28,
    aliases: ['vinos-bebidas', 'bebidas'],
  },
  {
    slug: 'frutas-verduras',
    label: 'Frutas & Verduras',
    shortLabel: 'Frutas',
    icon: Apple,
    bg: 'bg-lime-50',
    color: 'text-lime-700',
    border: 'border-lime-100',
    description: 'Producto de temporada, huerta local y variedad real.',
    fallbackCount: 32,
    aliases: ['frutas-verduras'],
  },
  {
    slug: 'especias-condimentos',
    label: 'Especias & Condimentos',
    shortLabel: 'Especias',
    icon: Flame,
    bg: 'bg-red-50',
    color: 'text-red-700',
    border: 'border-red-100',
    description: 'Mezclas, sales, salsas y condimentos para cocina con caracter.',
    fallbackCount: 24,
    aliases: ['especias-condimentos', 'salsas-condimentos'],
  },
  {
    slug: 'cafe-te',
    label: 'Cafe & Te',
    shortLabel: 'Cafe',
    icon: Coffee,
    bg: 'bg-stone-100',
    color: 'text-stone-700',
    border: 'border-stone-200',
    description: 'Tuestes pequenos, infusiones cuidadas y aroma recien hecho.',
    fallbackCount: 18,
    aliases: ['cafe-te', 'cafe-infusiones'],
  },
  {
    slug: 'snacks-frutos-secos',
    label: 'Snacks & Frutos Secos',
    shortLabel: 'Snacks',
    icon: Cookie,
    bg: 'bg-orange-50',
    color: 'text-orange-700',
    border: 'border-orange-100',
    description: 'Picoteo de calidad, frutos secos tostados y snack sin relleno.',
    fallbackCount: 26,
    aliases: ['snacks-frutos-secos', 'frutos-secos-snacks', 'snacks-saludables', 'frutos-secos', 'palomitas', 'barritas-energeticas', 'chips-vegetales', 'snacks-proteicos'],
  },
  {
    slug: 'orgánico-eco',
    label: 'Orgánico & Eco',
    shortLabel: 'Orgánico',
    icon: Leaf,
    bg: 'bg-green-50',
    color: 'text-green-700',
    border: 'border-green-100',
    description: 'Seleccion eco con certificación y productores que cuidan el origen.',
    fallbackCount: 17,
    aliases: ['orgánico-eco', 'orgánico'],
  },
  {
    slug: 'importados-premium',
    label: 'Importados Premium',
    shortLabel: 'Importados',
    icon: Globe2,
    bg: 'bg-sky-50',
    color: 'text-sky-700',
    border: 'border-sky-100',
    description: 'Productos internacionales ya en España, seleccionados por importadores verificados.',
    fallbackCount: 14,
    aliases: ['importados-premium', 'ingredientes-gourmet'],
  },
  {
    slug: 'congelados',
    label: 'Congelados',
    shortLabel: 'Congelados',
    icon: Snowflake,
    bg: 'bg-cyan-50',
    color: 'text-cyan-700',
    border: 'border-cyan-100',
    description: 'Congelado bien hecho, listo para envio y sin perder calidad.',
    fallbackCount: 11,
    aliases: ['congelados'],
  },
  // ── New categories ────────────────────────────────────────────────────
  {
    slug: 'bebidas-naturales',
    label: 'Bebidas naturales',
    shortLabel: 'Bebidas',
    icon: Droplets,
    bg: 'bg-blue-50',
    color: 'text-blue-700',
    border: 'border-blue-100',
    description: 'Zumos naturales, bebidas vegetales, kombucha y funcionales sin alcohol.',
    fallbackCount: 22,
    aliases: ['bebidas-naturales', 'zumos-naturales', 'bebidas-vegetales', 'kombucha', 'bebidas-funcionales'],
  },
  {
    slug: 'proteina-fitness',
    label: 'Proteina y Fitness',
    shortLabel: 'Fitness',
    icon: Dumbbell,
    bg: 'bg-violet-50',
    color: 'text-violet-700',
    border: 'border-violet-100',
    description: 'Proteina vegetal, whey, pre-workout, post-workout y recovery.',
    fallbackCount: 19,
    aliases: ['proteina-fitness', 'proteina-vegetal', 'proteina-whey', 'pre-workout', 'post-workout', 'recovery', 'fitness'],
  },
  {
    slug: 'alimentacion-infantil',
    label: 'Alimentacion infantil',
    shortLabel: 'Infantil',
    icon: Baby,
    bg: 'bg-pink-50',
    color: 'text-pink-700',
    border: 'border-pink-100',
    description: 'Papillas, snacks infantiles, leches y pures para los mas pequenos.',
    fallbackCount: 15,
    aliases: ['alimentacion-infantil', 'papillas', 'snacks-infantiles', 'leches-infantiles', 'pures-infantiles', 'bebe'],
  },
  {
    slug: 'mascotas',
    label: 'Mascotas',
    shortLabel: 'Mascotas',
    icon: Dog,
    bg: 'bg-amber-50',
    color: 'text-amber-800',
    border: 'border-amber-100',
    description: 'Comida para perros y gatos, snacks y suplementos naturales.',
    fallbackCount: 12,
    aliases: ['mascotas', 'comida-perros', 'comida-gatos', 'snacks-mascotas', 'suplementos-mascotas'],
  },
  {
    slug: 'sin-gluten',
    label: 'Sin gluten',
    shortLabel: 'Sin gluten',
    icon: WheatOff,
    bg: 'bg-teal-50',
    color: 'text-teal-700',
    border: 'border-teal-100',
    description: 'Productos 100% libres de gluten, aptos para celiacos e intolerantes.',
    fallbackCount: 20,
    aliases: ['sin-gluten', 'gluten-free', 'celiaco'],
  },
  {
    slug: 'sin-azucar',
    label: 'Sin azucar',
    shortLabel: 'Sin azucar',
    icon: Leaf,
    bg: 'bg-lime-50',
    color: 'text-lime-800',
    border: 'border-lime-100',
    description: 'Sin azucares anadidos, opciones keto y endulzantes naturales.',
    fallbackCount: 16,
    aliases: ['sin-azucar', 'sugar-free', 'keto', 'sin-azucares'],
  },
  {
    slug: 'vegano',
    label: 'Vegano',
    shortLabel: 'Vegano',
    icon: Leaf,
    bg: 'bg-green-50',
    color: 'text-green-800',
    border: 'border-green-200',
    description: 'Alimentacion 100% vegetal, certificada y con origen claro.',
    fallbackCount: 23,
    aliases: ['vegano', 'vegan', 'vegetariano', 'plant-based'],
  },
  {
    slug: 'superfoods',
    label: 'Superfoods',
    shortLabel: 'Superfoods',
    icon: Zap,
    bg: 'bg-yellow-50',
    color: 'text-yellow-800',
    border: 'border-yellow-200',
    description: 'Semillas, algas, adaptogenos y superalimentos de alta densidad nutricional.',
    fallbackCount: 13,
    aliases: ['superfoods', 'superfood', 'semillas', 'algas', 'adaptogenos'],
  },
];

// ── Full taxonomy tree (parents + subcategories) ───────────────────────────
export const PRODUCT_TAXONOMY = [
  {
    slug: 'snacks-frutos-secos',
    label: 'Snacks',
    subcategories: [
      { slug: 'palomitas', label: 'Palomitas' },
      { slug: 'frutos-secos', label: 'Frutos secos' },
      { slug: 'barritas-energeticas', label: 'Barritas energeticas' },
      { slug: 'galletas-saludables', label: 'Galletas saludables' },
      { slug: 'chips-vegetales', label: 'Chips vegetales' },
      { slug: 'snacks-proteicos', label: 'Snacks proteicos' },
    ],
  },
  {
    slug: 'bebidas-naturales',
    label: 'Bebidas',
    subcategories: [
      { slug: 'zumos-naturales', label: 'Zumos naturales' },
      { slug: 'bebidas-vegetales', label: 'Bebidas vegetales' },
      { slug: 'kombucha', label: 'Kombucha' },
      { slug: 'te', label: 'Te' },
      { slug: 'cafe', label: 'Cafe' },
      { slug: 'bebidas-funcionales', label: 'Bebidas funcionales' },
    ],
  },
  {
    slug: 'conservas-mermeladas',
    label: 'Desayuno',
    subcategories: [
      { slug: 'granola', label: 'Granola' },
      { slug: 'cereales', label: 'Cereales' },
      { slug: 'muesli', label: 'Muesli' },
      { slug: 'crema-frutos-secos', label: 'Crema de frutos secos' },
      { slug: 'miel', label: 'Miel' },
      { slug: 'mermeladas', label: 'Mermeladas' },
    ],
  },
  {
    slug: 'especias-condimentos',
    label: 'Cocina',
    subcategories: [
      { slug: 'aceite-oliva', label: 'Aceite de oliva' },
      { slug: 'vinagre', label: 'Vinagre' },
      { slug: 'salsas', label: 'Salsas' },
      { slug: 'condimentos', label: 'Condimentos' },
      { slug: 'especias', label: 'Especias' },
    ],
  },
  {
    slug: 'proteina-fitness',
    label: 'Fitness',
    subcategories: [
      { slug: 'proteina-vegetal', label: 'Proteina vegetal' },
      { slug: 'proteina-whey', label: 'Proteina whey' },
      { slug: 'pre-workout', label: 'Pre-workout' },
      { slug: 'post-workout', label: 'Post-workout' },
      { slug: 'recovery', label: 'Recovery' },
    ],
  },
  {
    slug: 'alimentacion-infantil',
    label: 'Infantil',
    subcategories: [
      { slug: 'papillas', label: 'Papillas' },
      { slug: 'snacks-infantiles', label: 'Snacks infantiles' },
      { slug: 'leches-infantiles', label: 'Leches infantiles' },
      { slug: 'pures-infantiles', label: 'Pures infantiles' },
    ],
  },
  {
    slug: 'mascotas',
    label: 'Mascotas',
    subcategories: [
      { slug: 'comida-perros', label: 'Comida perros' },
      { slug: 'comida-gatos', label: 'Comida gatos' },
      { slug: 'snacks-mascotas', label: 'Snacks mascotas' },
      { slug: 'suplementos-mascotas', label: 'Suplementos mascotas' },
    ],
  },
  {
    slug: 'dietas-especiales',
    label: 'Dietas especiales',
    subcategories: [
      { slug: 'sin-gluten', label: 'Sin gluten' },
      { slug: 'sin-azucar', label: 'Sin azucar' },
      { slug: 'keto', label: 'Keto' },
      { slug: 'vegano', label: 'Vegano' },
      { slug: 'bio-ecologico', label: 'Bio ecologico' },
    ],
  },
];

export const getCategoryConfig = (slug) => (
  CATEGORY_CONFIG.find((category) => category.slug === slug)
  || CATEGORY_CONFIG.find((category) => category.aliases.includes(slug))
  || null
);

export const getCategoryLabel = (slug) => getCategoryConfig(slug)?.label || slug;

export const productMatchesCategory = (product, categorySlug) => {
  const category = getCategoryConfig(categorySlug);
  if (!category || !product) return false;
  return category.aliases.includes(product.category);
};

export const getProductsForCategory = (products = [], categorySlug) => (
  products.filter((product) => productMatchesCategory(product, categorySlug))
);
