import {
  Apple,
  Beef,
  Coffee,
  Cookie,
  Croissant,
  Droplets,
  Flame,
  Globe2,
  Leaf,
  Milk,
  Package,
  Snowflake,
  Wine,
} from 'lucide-react';

export const CATEGORY_CONFIG = [
  {
    slug: 'aceites-vinagres',
    label: 'Aceites & Vinagres',
    shortLabel: 'Aceites',
    icon: Droplets,
    bg: 'bg-emerald-50',
    color: 'text-emerald-700',
    border: 'border-emerald-100',
    description: 'Aceites de oliva, vinagres artesanos y aliños con origen claro.',
    fallbackCount: 47,
    aliases: ['aceites-vinagres', 'aceite-condimentos'],
  },
  {
    slug: 'conservas-mermeladas',
    label: 'Conservas & Mermeladas',
    shortLabel: 'Conservas',
    icon: Package,
    bg: 'bg-amber-50',
    color: 'text-amber-700',
    border: 'border-amber-100',
    description: 'Tarros pequeños, recetas lentas y sabor de despensa bien hecha.',
    fallbackCount: 34,
    aliases: ['conservas-mermeladas', 'conservas'],
  },
  {
    slug: 'quesos-lacteos',
    label: 'Quesos & Lacteos',
    shortLabel: 'Quesos',
    icon: Milk,
    bg: 'bg-yellow-50',
    color: 'text-yellow-700',
    border: 'border-yellow-100',
    description: 'Quesos curados, yogures y lacteos de pequenos elaboradores.',
    fallbackCount: 29,
    aliases: ['quesos-lacteos', 'quesos', 'lacteos'],
  },
  {
    slug: 'embutidos-curados',
    label: 'Embutidos & Curados',
    shortLabel: 'Embutidos',
    icon: Beef,
    bg: 'bg-rose-50',
    color: 'text-rose-700',
    border: 'border-rose-100',
    description: 'Jamones, lomos y curados con elaboracion lenta y trazable.',
    fallbackCount: 21,
    aliases: ['embutidos-curados', 'carnes-huevos'],
  },
  {
    slug: 'panaderia-dulces',
    label: 'Panaderia & Dulces',
    shortLabel: 'Panaderia',
    icon: Croissant,
    bg: 'bg-orange-50',
    color: 'text-orange-700',
    border: 'border-orange-100',
    description: 'Hornadas artesanas, galletas honestas y dulces de obrador.',
    fallbackCount: 39,
    aliases: ['panaderia-dulces', 'panaderia'],
  },
  {
    slug: 'vinos-bebidas',
    label: 'Vinos & Bebidas',
    shortLabel: 'Bebidas',
    icon: Wine,
    bg: 'bg-fuchsia-50',
    color: 'text-fuchsia-700',
    border: 'border-fuchsia-100',
    description: 'Botellas con historia, bodegas pequeñas y bebidas de autor.',
    fallbackCount: 28,
    aliases: ['vinos-bebidas', 'bebidas'],
  },
  {
    slug: 'frutas-verduras',
    label: 'Frutas & Verduras',
    shortLabel: 'Frutas',
    icon: Apple,
    bg: 'bg-lime-50',
    color: 'text-lime-700',
    border: 'border-lime-100',
    description: 'Producto de temporada, huerta local y variedad real.',
    fallbackCount: 32,
    aliases: ['frutas-verduras'],
  },
  {
    slug: 'especias-condimentos',
    label: 'Especias & Condimentos',
    shortLabel: 'Especias',
    icon: Flame,
    bg: 'bg-red-50',
    color: 'text-red-700',
    border: 'border-red-100',
    description: 'Mezclas, sales, salsas y condimentos para cocina con caracter.',
    fallbackCount: 24,
    aliases: ['especias-condimentos', 'salsas-condimentos'],
  },
  {
    slug: 'cafe-te',
    label: 'Cafe & Te',
    shortLabel: 'Cafe',
    icon: Coffee,
    bg: 'bg-stone-100',
    color: 'text-stone-700',
    border: 'border-stone-200',
    description: 'Tuestes pequenos, infusiones cuidadas y aroma recien hecho.',
    fallbackCount: 18,
    aliases: ['cafe-te', 'cafe-infusiones'],
  },
  {
    slug: 'snacks-frutos-secos',
    label: 'Snacks & Frutos Secos',
    shortLabel: 'Snacks',
    icon: Cookie,
    bg: 'bg-orange-50',
    color: 'text-orange-700',
    border: 'border-orange-100',
    description: 'Picoteo de calidad, frutos secos tostados y snack sin relleno.',
    fallbackCount: 26,
    aliases: ['snacks-frutos-secos', 'frutos-secos-snacks'],
  },
  {
    slug: 'organico-eco',
    label: 'Organico & Eco',
    shortLabel: 'Organico',
    icon: Leaf,
    bg: 'bg-green-50',
    color: 'text-green-700',
    border: 'border-green-100',
    description: 'Seleccion eco con certificacion y productores que cuidan el origen.',
    fallbackCount: 17,
    aliases: ['organico-eco', 'organico'],
  },
  {
    slug: 'importados-premium',
    label: 'Importados Premium',
    shortLabel: 'Importados',
    icon: Globe2,
    bg: 'bg-sky-50',
    color: 'text-sky-700',
    border: 'border-sky-100',
    description: 'Productos internacionales ya en Espana, seleccionados por importadores verificados.',
    fallbackCount: 14,
    aliases: ['importados-premium'],
  },
  {
    slug: 'congelados',
    label: 'Congelados',
    shortLabel: 'Congelados',
    icon: Snowflake,
    bg: 'bg-cyan-50',
    color: 'text-cyan-700',
    border: 'border-cyan-100',
    description: 'Congelado bien hecho, listo para envio y sin perder calidad.',
    fallbackCount: 11,
    aliases: ['congelados'],
  },
];

export const getCategoryConfig = (slug) => (
  CATEGORY_CONFIG.find((category) => category.slug === slug)
  || CATEGORY_CONFIG.find((category) => category.aliases.includes(slug))
  || null
);

export const getCategoryLabel = (slug) => getCategoryConfig(slug)?.label || slug;

export const productMatchesCategory = (product, categorySlug) => {
  const category = getCategoryConfig(categorySlug);
  if (!category || !product) return false;
  return category.aliases.includes(product.category);
};

export const getProductsForCategory = (products = [], categorySlug) => (
  products.filter((product) => productMatchesCategory(product, categorySlug))
);
